"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { toPng, toBlob } from "html-to-image";
import { toast } from "sonner";
import type { Analysis } from "@/lib/analysis/types";
import { AI_EMOJI } from "@/lib/analysis/prompt";
import {
  WelcomeCard,
  PersonalityCard,
  ThinkingCard,
  ScoresCard,
  CommunicationCard,
  InterestsCard,
  StrengthsCard,
  FunFactsCard,
  AchievementsCard,
  CareerCard,
  PredictionsCard,
  CardShell,
} from "./cards";
import { Button } from "@/components/ui/button";
import { ThemeToggle } from "@/components/ui/theme-toggle";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
  ChevronLeft,
  ChevronRight,
  Download,
  Share2,
  RefreshCw,
  Swords,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface ViewerProps {
  id: string;
  code?: string | null;
  username: string;
  aiUsed: string;
  aiEmoji: string;
  analysis: Analysis;
}

const CARD_TITLES = [
  "Welcome",
  "Personality",
  "Thinking Style",
  "Scores",
  "Communication",
  "Interests",
  "Strengths",
  "Fun Facts",
  "Achievements",
  "Career",
  "Predictions",
  "Your Share Card",
];

function EngineBadge({ engine }: { engine?: string }) {
  if (engine === "groq")
    return (
      <p className="mt-3 inline-flex items-center gap-1.5 text-[11px] uppercase tracking-[0.2em] text-white/60">
        ⚡ Analyzed with Groq
      </p>
    );
  if (engine === "openai")
    return (
      <p className="mt-3 inline-flex items-center gap-1.5 text-[11px] uppercase tracking-[0.2em] text-white/60">
        ✦ Analyzed with OpenAI
      </p>
    );
  return (
    <p className="mt-3 text-[11px] uppercase tracking-[0.2em] text-white/60">
      ⚙️ Local analysis mode
    </p>
  );
}

function ShareCardView({
  username,
  aiUsed,
  analysis,
  code,
}: {
  username: string;
  aiUsed: string;
  analysis: Analysis;
  code?: string | null;
}) {
  const a = analysis;
  return (
    <CardShell theme="share">
      <div className="my-auto text-center">
        <p className="text-xs uppercase tracking-[0.3em] text-white/60">Your 2026 AI Wrapped</p>
        <h2 className="mt-2 font-display text-5xl md:text-6xl font-bold text-gradient-bright">
          {username}
        </h2>
        <p className="mt-2 text-white/70">
          {AI_EMOJI[aiUsed] ?? "🤖"} {aiUsed}
        </p>

        {code && (
          <div className="mt-5 inline-flex items-center gap-3 rounded-full border border-white/30 bg-white/15 px-5 py-2.5 backdrop-blur-sm">
            <span className="text-white/60">CODE: </span>
            <span className="font-display text-xl font-bold tracking-[0.2em]">{code}</span>
          </div>
        )}

        <div className="mt-6 grid grid-cols-2 gap-3 text-left">
          {[
            ["AI Personality", a.personality.personalityType],
            ["Top Strength", a.strengths[0] ?? "—"],
            ["Top Interest", a.interests.topTopics[0] ?? "—"],
            ["Best Badge", a.achievements[0] ?? "—"],
          ].map(([label, value]) => (
            <div
              key={label}
              className="rounded-2xl border border-white/20 bg-white/10 p-4 backdrop-blur-sm"
            >
              <div className="text-[11px] uppercase tracking-wider text-white/55">{label}</div>
              <div className="mt-1 font-semibold text-sm leading-snug">{value}</div>
            </div>
          ))}
        </div>

        <div className="mt-6 inline-flex items-center gap-3 rounded-full border border-white/25 bg-black/30 px-6 py-3 backdrop-blur-sm">
          <span className="text-xs uppercase tracking-wider text-white/60">Overall</span>
          <span className="font-display text-3xl font-bold text-gradient-bright">{a.scores.overall}</span>
          <span className="text-xs text-white/60">/100</span>
        </div>

        <EngineBadge engine={a.profile.engine} />

        <p className="mt-6 text-[11px] uppercase tracking-[0.25em] text-white/60">
          Generated by AI Wrapped
        </p>
        <p className="mt-2 text-[11px] uppercase tracking-[0.25em] text-white/50">
          Built by Alite ·{" "}
          <a
            href="https://wa.me/2349154681851?text=Well%20done%20on%20AI%20Wrapped%2C%20Alite!"
            target="_blank"
            rel="noopener noreferrer"
            className="text-emerald-300/90 hover:text-emerald-200 transition-colors normal-case tracking-normal"
          >
            Say hi on WhatsApp 💬
          </a>
        </p>
      </div>
    </CardShell>
  );
}

export default function WrappedViewer(props: ViewerProps) {
  const { id, code, username, aiUsed, aiEmoji, analysis } = props;
  const router = useRouter();
  const [index, setIndex] = useState(0);
  const [busy, setBusy] = useState<"download" | "share" | null>(null);
  const [compareOpen, setCompareOpen] = useState(false);
  const [friendCode, setFriendCode] = useState("");
  const cardRef = useRef<HTMLDivElement>(null);
  const total = 12;

  const captions = useMemo(() => {
    return [
      `${username}'s AI Wrapped — discover how AI sees you ✨`,
      `My AI personality is ${analysis.personality.personalityType} (${analysis.personality.aiArchetype})`,
      `My thinking style: ${analysis.personality.thinkingStyle} — how I think, per AI Wrapped`,
      `My AI Power Level: ${analysis.scores.overall}/100 🚀`,
      `My AI voiceprint: I mostly say "${analysis.language.mostUsedWord}"`,
      `I'm into ${analysis.interests.topTopics.slice(0, 3).join(", ")}`,
      `My top strength: ${analysis.strengths[0] ?? "Curiosity"} 💪`,
      `Fun fact about me: ${analysis.fun.funniestInsight}`,
      `Badges I unlocked: ${analysis.achievements.slice(0, 3).join(", ")} 🏅`,
      `Best career match for me: ${analysis.career.topMatch}`,
      `My next skill: ${analysis.prediction.nextSkill} 🚀`,
      `My AI personality is ${analysis.personality.personalityType} with an overall score of ${analysis.scores.overall}. Discover how AI sees you`,
    ];
  }, [analysis, username]);

  const next = useCallback(() => setIndex((i) => Math.min(i + 1, total - 1)), [total]);
  const prev = useCallback(() => setIndex((i) => Math.max(i - 1, 0)), []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") next();
      if (e.key === "ArrowLeft") prev();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [next, prev]);

  const fileName = useMemo(() => {
    const slug = CARD_TITLES[index]
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    return `${username.toLowerCase().replace(/\s+/g, "-")}-${slug}.png`;
  }, [index, username]);

  const downloadPng = async () => {
    if (!cardRef.current) return;
    setBusy("download");
    try {
      const dataUrl = await toPng(cardRef.current, {
        pixelRatio: 2,
        cacheBust: true,
      });
      const link = document.createElement("a");
      link.download = fileName;
      link.href = dataUrl;
      link.click();
      toast.success(`Saved ${CARD_TITLES[index]} as PNG!`);
    } catch {
      toast.error("Couldn't render the image. Try again.");
    } finally {
      setBusy(null);
    }
  };

  const shareCard = async () => {
    if (!cardRef.current) return;
    setBusy("share");
    try {
      const blob = await toBlob(cardRef.current, {
        pixelRatio: 2,
        cacheBust: true,
      });
      if (!blob) throw new Error("no blob");
      const file = new File([blob], fileName, { type: "image/png" });
      const caption = captions[index];
      if (typeof navigator.share === "function" && navigator.canShare?.({ files: [file] })) {
        try {
          await navigator.share({ files: [file], title: `${username}'s AI Wrapped`, text: caption });
          return;
        } catch {
          /* user cancelled */
        }
      }
      const link = document.createElement("a");
      link.download = file.name;
      link.href = URL.createObjectURL(blob);
      link.click();
      URL.revokeObjectURL(link.href);
      try {
        await navigator.clipboard.writeText(caption);
        toast.success("Image saved + caption copied!");
      } catch {
        toast.success("Image saved!");
      }
    } catch {
      toast.error("Couldn't render the image. Try again.");
    } finally {
      setBusy(null);
    }
  };

  const shareLink = async () => {
    const url = `${window.location.origin}/wrapped/${id}`;
    const text = `${captions[total - 1]} → ${url}`;
    if (navigator.share) {
      try {
        await navigator.share({ title: `${username}'s AI Wrapped`, text, url });
        return;
      } catch {
        /* user cancelled */
      }
    }
    try {
      await navigator.clipboard.writeText(text);
      toast.success("Link copied to clipboard!");
    } catch {
      toast.error("Couldn't copy automatically.");
    }
  };

  const startCompare = async () => {
    const fc = friendCode.trim().toUpperCase();
    if (fc.length < 4) return;
    try {
      const res = await fetch(`/api/lookup?code=${encodeURIComponent(fc)}`);
      if (res.status === 404) {
        toast.error(`No wrap found with code "${fc}". Double-check it.`);
        return;
      }
      if (!res.ok) throw new Error("lookup failed");
      setCompareOpen(false);
      router.push(`/compare?me=${encodeURIComponent(code ?? "")}&them=${encodeURIComponent(fc)}`);
    } catch {
      toast.error("Couldn't reach the compare service.");
    }
  };

  const cards = [
    <WelcomeCard key="w" username={username} aiUsed={aiUsed} aiEmoji={aiEmoji} date={new Date().getFullYear().toString()} />,
    <PersonalityCard key="p" analysis={analysis} />,
    <ThinkingCard key="t" analysis={analysis} />,
    <ScoresCard key="s" analysis={analysis} />,
    <CommunicationCard key="c" analysis={analysis} />,
    <InterestsCard key="i" analysis={analysis} />,
    <StrengthsCard key="st" analysis={analysis} />,
    <FunFactsCard key="f" analysis={analysis} />,
    <AchievementsCard key="a" analysis={analysis} />,
    <CareerCard key="ca" analysis={analysis} />,
    <PredictionsCard key="pr" analysis={analysis} />,
    <ShareCardView key="share" username={username} aiUsed={aiUsed} analysis={analysis} code={code} />,
  ];

  return (
    <main className="relative flex-1 min-h-screen flex flex-col overflow-hidden">
      <div className="pointer-events-none fixed inset-0 -z-10">
        <div className="absolute top-0 left-1/4 size-[30rem] rounded-full bg-violet-400/30 dark:bg-violet-600/20 blur-[130px] animate-float-slow" />
        <div className="absolute bottom-0 right-0 size-[26rem] rounded-full bg-fuchsia-400/25 dark:bg-fuchsia-600/20 blur-[130px] animate-float-slower" />
      </div>

      <header className="fixed top-0 inset-x-0 z-40 px-4 pt-4">
        <div className="mx-auto max-w-5xl glass rounded-full px-4 py-2.5 flex items-center justify-between gap-3">
          <Link href="/" className="flex items-center gap-2 font-display font-bold text-sm shrink-0">
            🪄 AI Wrapped
          </Link>
          <div className="hidden sm:flex flex-1 justify-center gap-1.5">
            {CARD_TITLES.map((t, i) => (
              <button
                key={t}
                title={t}
                onClick={() => setIndex(i)}
                className={cn(
                  "h-1.5 rounded-full transition-all",
                  i === index ? "w-6 bg-gradient-to-r from-violet-500 to-fuchsia-500 dark:from-violet-400 dark:to-fuchsia-400" : "w-2 bg-black/15 dark:bg-white/15 hover:bg-black/30 dark:hover:bg-white/30"
                )}
              />
            ))}
          </div>
          <div className="flex items-center gap-2 shrink-0">
            <span className="text-xs text-muted-foreground font-mono tabular-nums">
              {index + 1}/{total}
            </span>
            <ThemeToggle />
          </div>
        </div>
      </header>

      <div className="flex-1 flex flex-col justify-center px-4 pt-20 pb-32">
        <div className="mx-auto w-full max-w-3xl h-[58vh] md:h-[66vh] relative">
          <AnimatePresence mode="wait">
            <motion.div
              key={index}
              initial={{ opacity: 0, x: 80, rotate: 1.5 }}
              animate={{ opacity: 1, x: 0, rotate: 0 }}
              exit={{ opacity: 0, x: -80, rotate: -1.5 }}
              transition={{ duration: 0.35, ease: "easeOut" }}
              drag="x"
              dragConstraints={{ left: 0, right: 0 }}
              dragElastic={0.6}
              onDragEnd={(_, info) => {
                if (info.offset.x < -80) next();
                else if (info.offset.x > 80) prev();
              }}
              className="h-full cursor-grab active:cursor-grabbing touch-pan-y"
            >
              <div ref={cardRef} className="h-full">
                {cards[index]}
              </div>
            </motion.div>
          </AnimatePresence>
        </div>

        <div className="fixed bottom-0 inset-x-0 z-40">
          <div className="mx-auto max-w-3xl px-4 pb-5">
            <div className="glass rounded-2xl p-3 flex items-center gap-2">
              <Button variant="ghost" size="icon" onClick={prev} disabled={index === 0} className="shrink-0">
                <ChevronLeft className="size-5" />
              </Button>
              <div className="flex-1 text-center min-w-0">
                {index === total - 1 ? (
                  <div className="flex items-center justify-center gap-2 flex-wrap">
                    <Button size="sm" onClick={downloadPng} disabled={busy !== null} className="bg-gradient-to-r from-violet-600 to-fuchsia-600">
                      <Download className="mr-1.5 size-4" />
                      {busy === "download" ? "Rendering..." : "Download PNG"}
                    </Button>
                    <Button size="sm" variant="outline" onClick={shareLink}>
                      <Share2 className="mr-1.5 size-4" /> Share
                    </Button>
                    <Button size="sm" variant="outline" onClick={() => setCompareOpen(true)} disabled={!code}>
                      <Swords className="mr-1.5 size-4" /> Compare
                    </Button>
                    <Button size="sm" variant="ghost" render={<Link href="/generate" />}>
                      <RefreshCw className="mr-1.5 size-4" /> Generate Again
                    </Button>
                  </div>
                ) : (
                  <div className="min-w-0 px-2">
                    <span className="text-sm text-muted-foreground font-display font-semibold tracking-wide block truncate">
                      {CARD_TITLES[index]}
                    </span>
                    <span className="text-[11px] text-muted-foreground/80 block truncate">
                      {captions[index]}
                    </span>
                  </div>
                )}
              </div>
              <div className="flex items-center gap-1 shrink-0">
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={downloadPng}
                  disabled={busy !== null || index === total - 1}
                  title="Download this card"
                  className="size-8"
                >
                  <Download className="size-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={shareCard}
                  disabled={busy !== null || index === total - 1}
                  title="Share this card to apps"
                  className="size-8"
                >
                  <Share2 className="size-4" />
                </Button>
              </div>
              <Button variant="ghost" size="icon" onClick={next} disabled={index === total - 1} className="shrink-0">
                <ChevronRight className="size-5" />
              </Button>
            </div>
          </div>
        </div>
      </div>

      <Dialog open={compareOpen} onOpenChange={setCompareOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Compare with a friend 🥊</DialogTitle>
            <DialogDescription>
              Ask your friend for their AI Wrapped code and paste it below. Your code:{" "}
              <span className="inline-flex items-center gap-1 font-mono font-bold text-foreground">
                {code ?? "—"}
              </span>
            </DialogDescription>
          </DialogHeader>
          <Input
            value={friendCode}
            onChange={(e) => setFriendCode(e.target.value.toUpperCase())}
            placeholder="e.g. KC7F2M"
            maxLength={6}
            className="h-12 text-center font-mono text-lg uppercase tracking-[0.3em]"
            onKeyDown={(e) => {
              if (e.key === "Enter" && friendCode.length >= 4) startCompare();
            }}
          />
          <DialogFooter>
            <Button variant="outline" onClick={() => setCompareOpen(false)}>Cancel</Button>
            <Button
              disabled={friendCode.trim().length < 4}
              onClick={() => startCompare()}
              className="bg-gradient-to-r from-violet-600 to-fuchsia-600"
            >
              <Swords className="mr-1.5 size-4" /> Compare
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </main>
  );
}
