"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Link from "next/link";
import { toPng } from "html-to-image";
import { toast } from "sonner";
import type { Analysis } from "@/lib/analysis/types";
import { AI_EMOJI } from "@/lib/analysis/prompt";
import {
  WelcomeCard,
  PersonalityCard,
  ThinkingCard,
  ScoresCard,
  CommunicationCard,
  InterestsCard,
  StrengthsCard,
  FunFactsCard,
  AchievementsCard,
  CareerCard,
  PredictionsCard,
  CardShell,
} from "./cards";
import { Button } from "@/components/ui/button";
import { ChevronLeft, ChevronRight, Download, Share2, RefreshCw } from "lucide-react";
import { cn } from "@/lib/utils";

interface ViewerProps {
  id: string;
  username: string;
  aiUsed: string;
  aiEmoji: string;
  analysis: Analysis;
}

const CARD_TITLES = [
  "Welcome",
  "Personality",
  "Thinking Style",
  "Scores",
  "Communication",
  "Interests",
  "Strengths",
  "Fun Facts",
  "Achievements",
  "Career",
  "Predictions",
  "Your Share Card",
];

function ShareCardView({
  username,
  aiUsed,
  analysis,
}: {
  username: string;
  aiUsed: string;
  analysis: Analysis;
}) {
  const a = analysis;
  return (
    <CardShell accent="from-violet-600/50 via-fuchsia-600/30 to-cyan-500/20">
      <div className="my-auto text-center">
        <p className="text-xs uppercase tracking-[0.3em] text-muted-foreground">Your 2026 AI Wrapped</p>
        <h2 className="mt-2 font-display text-5xl md:text-6xl font-bold text-gradient">{username}</h2>
        <p className="mt-2 text-muted-foreground">
          {AI_EMOJI[aiUsed] ?? "🤖"} {aiUsed}
        </p>

        <div className="mt-8 grid grid-cols-2 gap-3 text-left">
          {[
            ["AI Personality", a.personality.personalityType],
            ["Top Strength", a.strengths[0] ?? "—"],
            ["Top Interest", a.interests.topTopics[0] ?? "—"],
            ["Best Badge", a.achievements[0] ?? "—"],
          ].map(([label, value]) => (
            <div key={label} className="glass rounded-2xl p-4">
              <div className="text-[11px] uppercase tracking-wider text-muted-foreground">{label}</div>
              <div className="mt-1 font-semibold text-sm leading-snug">{value}</div>
            </div>
          ))}
        </div>

        <div className="mt-6 inline-flex items-center gap-3 rounded-full border border-white/15 bg-white/[0.06] px-6 py-3">
          <span className="text-xs uppercase tracking-wider text-muted-foreground">Overall</span>
          <span className="font-display text-3xl font-bold text-gradient">{a.scores.overall}</span>
          <span className="text-xs text-muted-foreground">/100</span>
        </div>

        <p className="mt-8 text-[11px] uppercase tracking-[0.25em] text-muted-foreground">
          Generated by AI Wrapped
        </p>
      </div>
    </CardShell>
  );
}

export default function WrappedViewer(props: ViewerProps) {
  const { id, username, aiUsed, aiEmoji, analysis } = props;
  const [index, setIndex] = useState(0);
  const [downloading, setDownloading] = useState(false);
  const shareRef = useRef<HTMLDivElement>(null);
  const total = 12;

  const next = useCallback(() => setIndex((i) => Math.min(i + 1, total - 1)), [total]);
  const prev = useCallback(() => setIndex((i) => Math.max(i - 1, 0)), []);

  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight") next();
      if (e.key === "ArrowLeft") prev();
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [next, prev]);

  const downloadPng = async () => {
    if (!shareRef.current) return;
    setDownloading(true);
    try {
      const dataUrl = await toPng(shareRef.current, {
        pixelRatio: 2,
        backgroundColor: "#0d0b14",
        cacheBust: true,
      });
      const link = document.createElement("a");
      link.download = `${username}-ai-wrapped.png`;
      link.href = dataUrl;
      link.click();
      toast.success("PNG downloaded!");
    } catch {
      toast.error("Couldn't render the image. Try again.");
    } finally {
      setDownloading(false);
    }
  };

  const share = async () => {
    const url = `${window.location.origin}/wrapped/${id}`;
    const text = `My AI personality is ${analysis.personality.personalityType} with an overall score of ${analysis.scores.overall}. Discover how AI sees you → ${url}`;
    if (navigator.share) {
      try {
        await navigator.share({ title: `${username}'s AI Wrapped`, text, url });
        return;
      } catch {
        /* user cancelled */
      }
    }
    try {
      await navigator.clipboard.writeText(text);
      toast.success("Link copied to clipboard!");
    } catch {
      toast.error("Couldn't copy automatically.");
    }
  };

  const cards = [
    <WelcomeCard key="w" username={username} aiUsed={aiUsed} aiEmoji={aiEmoji} date={new Date().getFullYear().toString()} />,
    <PersonalityCard key="p" analysis={analysis} />,
    <ThinkingCard key="t" analysis={analysis} />,
    <ScoresCard key="s" analysis={analysis} />,
    <CommunicationCard key="c" analysis={analysis} />,
    <InterestsCard key="i" analysis={analysis} />,
    <StrengthsCard key="st" analysis={analysis} />,
    <FunFactsCard key="f" analysis={analysis} />,
    <AchievementsCard key="a" analysis={analysis} />,
    <CareerCard key="ca" analysis={analysis} />,
    <PredictionsCard key="pr" analysis={analysis} />,
    <div key="share" ref={shareRef} className="h-full">
      <ShareCardView username={username} aiUsed={aiUsed} analysis={analysis} />
    </div>,
  ];

  return (
    <main className="relative flex-1 min-h-screen flex flex-col overflow-hidden">
      <div className="pointer-events-none fixed inset-0 -z-10">
        <div className="absolute top-0 left-1/4 size-[30rem] rounded-full bg-violet-600/20 blur-[130px] animate-float-slow" />
        <div className="absolute bottom-0 right-0 size-[26rem] rounded-full bg-fuchsia-600/20 blur-[130px] animate-float-slower" />
      </div>

      <header className="fixed top-0 inset-x-0 z-40 px-4 pt-4">
        <div className="mx-auto max-w-5xl glass rounded-full px-4 py-2.5 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-display font-bold text-sm">
            🪄 AI Wrapped
          </Link>
          <div className="hidden sm:flex gap-1.5">
            {CARD_TITLES.map((t, i) => (
              <button
                key={t}
                title={t}
                onClick={() => setIndex(i)}
                className={cn(
                  "h-1.5 rounded-full transition-all",
                  i === index ? "w-6 bg-gradient-to-r from-violet-400 to-fuchsia-400" : "w-2 bg-white/15 hover:bg-white/30"
                )}
              />
            ))}
          </div>
          <span className="text-xs text-muted-foreground font-mono tabular-nums">
            {index + 1}/{total}
          </span>
        </div>
      </header>

      <div className="flex-1 flex flex-col justify-center px-4 pt-20 pb-28">
        <div className="mx-auto w-full max-w-3xl h-[62vh] md:h-[68vh] relative">
          <AnimatePresence mode="wait">
            <motion.div
              key={index}
              initial={{ opacity: 0, x: 80, rotate: 1.5 }}
              animate={{ opacity: 1, x: 0, rotate: 0 }}
              exit={{ opacity: 0, x: -80, rotate: -1.5 }}
              transition={{ duration: 0.35, ease: "easeOut" }}
              drag="x"
              dragConstraints={{ left: 0, right: 0 }}
              dragElastic={0.6}
              onDragEnd={(_, info) => {
                if (info.offset.x < -80) next();
                else if (info.offset.x > 80) prev();
              }}
              className="h-full cursor-grab active:cursor-grabbing touch-pan-y"
            >
              {cards[index]}
            </motion.div>
          </AnimatePresence>
        </div>

        <div className="fixed bottom-0 inset-x-0 z-40">
          <div className="mx-auto max-w-3xl px-4 pb-5">
            <div className="glass rounded-2xl p-3 flex items-center gap-2">
              <Button variant="ghost" size="icon" onClick={prev} disabled={index === 0} className="shrink-0">
                <ChevronLeft className="size-5" />
              </Button>
              <div className="flex-1 text-center">
                {index === total - 1 ? (
                  <div className="flex items-center justify-center gap-2">
                    <Button size="sm" onClick={downloadPng} disabled={downloading} className="bg-gradient-to-r from-violet-600 to-fuchsia-600">
                      <Download className="mr-1.5 size-4" />
                      {downloading ? "Rendering..." : "Download PNG"}
                    </Button>
                    <Button size="sm" variant="outline" onClick={share}>
                      <Share2 className="mr-1.5 size-4" /> Share
                    </Button>
                    <Button size="sm" variant="ghost" render={<Link href="/generate" />}>
                      <RefreshCw className="mr-1.5 size-4" /> Generate Again
                    </Button>
                  </div>
                ) : (
                  <span className="text-sm text-muted-foreground font-display font-semibold tracking-wide">
                    {CARD_TITLES[index]}
                  </span>
                )}
              </div>
              <Button variant="ghost" size="icon" onClick={next} disabled={index === total - 1} className="shrink-0">
                <ChevronRight className="size-5" />
              </Button>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
