export const AI_OPTIONS: { value: string; emoji: string; description: string }[] = [
  { value: "ChatGPT", emoji: "🤖", description: "OpenAI's all-rounder" },
  { value: "Gemini", emoji: "✨", description: "Google's multi-modal mind" },
  { value: "Claude", emoji: "🧠", description: "Anthropic's thoughtful one" },
  { value: "Grok", emoji: "🚀", description: "X's witty speedster" },
  { value: "DeepSeek", emoji: "🔍", description: "The sharp open researcher" },
  { value: "Perplexity", emoji: "🌐", description: "Answers with sources" },
  { value: "Microsoft Copilot", emoji: "💼", description: "The workhorse" },
  { value: "Meta AI", emoji: "♾️", description: "Social-first assistant" },
  { value: "Qwen", emoji: "🧮", description: "Alibaba's all-rounder" },
  { value: "Kimi", emoji: "🌙", description: "The long-context master" },
  { value: "Mistral AI", emoji: "⚡", description: "Efficient and fast" },
  { value: "Other", emoji: "➕", description: "Something else entirely" },
];

export const AI_EMOJI: Record<string, string> = Object.fromEntries(
  AI_OPTIONS.map((o) => [o.value, o.emoji])
);

export const ENGINEERED_PROMPT = `Analyze my personality based on everything you know about me from our conversation history. Write a detailed, honest and insightful profile. Cover these areas:

1. My personality type and AI archetype (e.g. Strategic Thinker, Creative Visionary, Curious Explorer).
2. My thinking style, communication style, decision-making style, learning style and leadership style.
3. My top strengths (list 5) and my biggest growth areas (list 3).
4. My top interests and favorite domains of knowledge.
5. How productive I am, what I most often use you for, and roughly how many hours I save by using AI.
6. Which careers would fit me best (list 3, in order).
7. Fun insights: my signature prompt style, my most unexpected or wildest prompt, my biggest rabbit hole, my most creative moment, and one funny observation about how I use AI.
8. Which achievement badges I deserve (e.g. Researcher, Builder, Innovator, Creator, Night Owl, Knowledge Seeker, AI Power User).
9. Predictions: the next skill I will learn, my next challenge, and one book, one project, and one learning path you recommend for me.

Be specific. Use concrete examples from our actual conversations whenever possible. End with a fun fact about me.`;

export const ANALYSIS_SYSTEM_PROMPT = `You are the analysis engine behind "Aura", an app that reveals a person's AI personality based on a text they got from their favorite AI assistant. The text describes that person's personality, habits and interests (it was generated by asking an AI to profile them).

Your job: extract structured data from that text. Respond with ONLY a valid JSON object, no markdown, no commentary, matching this exact schema:

{
  "personality": {
    "personalityType": "short label like Strategic Thinker | Creative Visionary | Analytical Mind | Curious Explorer | Pragmatic Builder | Balanced Thinker",
    "aiArchetype": "short archetype like The Philosopher | The Builder | The Scientist | The Artist | The Explorer | The Advisor",
    "communicationStyle": "e.g. Direct, Storytelling, Precise, Playful, Thoughtful, Persuasive",
    "thinkingStyle": "e.g. Big-Picture, Detail-Oriented, First-Principles, Systems-Based, Intuitive",
    "learningStyle": "e.g. Visual, Hands-On, Reading-Based, Project-Based, Conversational",
    "decisionStyle": "e.g. Data-Driven, Gut-Feeling, Collaborative, Cautious, Decisive",
    "leadershipStyle": "e.g. Collaborative, Visionary, Servant, Commanding, Coaching",
    "confidenceLevel": "Low | Moderate | High | Very High",
    "curiosityLevel": "Low | Moderate | High | Very High",
    "creativityLevel": "Low | Moderate | High | Very High"
  },
  "scores": {
    "creativity": 0-100 number,
    "leadership": 0-100 number,
    "communication": 0-100 number,
    "learning": 0-100 number,
    "productivity": 0-100 number,
    "problemSolving": 0-100 number,
    "criticalThinking": 0-100 number,
    "innovation": 0-100 number
  },
  "language": {
    "mostUsedWord": "a common word this person uses",
    "mostUsedPhrase": "short phrase they often use",
    "vocabularyLevel": "Basic | Moderate | Rich | Advanced",
    "writingStyle": "e.g. Formal, Casual, Technical, Storytelling, Minimalist",
    "promptStyle": "e.g. Direct Commands, Detailed Briefs, Explorative Questions, Iterative",
    "questionStyle": "e.g. Open-Ended, Yes/No, Hypothetical, Follow-Up Chains",
    "averageComplexity": "Simple | Moderate | Complex"
  },
  "interests": {
    "topTopics": ["up to 10 topic words"],
    "topSubjects": ["up to 10 more specific subjects"],
    "favoriteDomain": "one broad domain",
    "mostDiscussedArea": "one area"
  },
  "productivity": {
    "estimatedHoursSaved": "e.g. '6 hours/week'",
    "mostCommonUse": "e.g. Coding, Writing, Research, Learning, Brainstorming",
    "researchLevel": "Low | Medium | High",
    "writingLevel": "Low | Medium | High",
    "codingLevel": "Low | Medium | High"
  },
  "career": {
    "topMatch": "career",
    "secondMatch": "career",
    "thirdMatch": "career"
  },
  "strengths": ["exactly 5 short strengths"],
  "improvement": ["exactly 3 short growth areas"],
  "fun": {
    "signaturePrompt": "their signature prompt style, e.g. 'Explain this like I'm five'",
    "mostUnexpectedPrompt": "their most unexpected or surprising use of AI",
    "biggestRabbitHole": "the topic they fall down rabbit holes on",
    "wildestQuestion": "their wildest or most creative question",
    "mostCreativeMoment": "their most creative moment with AI",
    "funniestInsight": "one funny insight about them"
  },
  "achievements": ["choose from: Researcher, Builder, Innovator, Creator, Explorer, Scholar, Problem Solver, AI Power User, Fast Learner, Night Owl, Knowledge Seeker, Question Machine"],
  "prediction": {
    "nextSkill": "the next skill they'll learn",
    "nextChallenge": "their next likely challenge",
    "bookRecommendation": "one book title",
    "projectRecommendation": "one project idea",
    "learningRecommendation": "one learning path"
  }
}

Rules:
- Infer everything from the provided text. Never invent facts the text contradicts; when the text is silent, pick the most plausible value.
- Scores must be integers between 0 and 100.
- Keep every string short and specific (strengths/improvements: 2-4 words each).
- The "achievements" field is an array of 4 to 8 badges chosen from the allowed list.
- Output ONLY the JSON object.`;

export function buildAnalysisUserPrompt(input: {
  username: string;
  aiUsed: string;
  text: string;
}): string {
  return `USERNAME: ${input.username}
AI USED: ${input.aiUsed}
TEXT TO ANALYZE:
"""${input.text}"""`;
}
